// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'account.dart';
import 'ftoken.dart';
import 'notification.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'provider.dart';
import 'settings.dart';
import 'wallet.dart';

class BackgroundState {
  final List<WalletInfo> wallets;
  final Map<BigInt, BackgroundNotificationState> notificationsWalletStates;
  final bool notificationsGlobalEnabled;
  final String locale;
  final int appearances;
  final List<NetworkConfigInfo> providers;

  const BackgroundState({
    required this.wallets,
    required this.notificationsWalletStates,
    required this.notificationsGlobalEnabled,
    required this.locale,
    required this.appearances,
    required this.providers,
  });

  @override
  int get hashCode =>
      wallets.hashCode ^
      notificationsWalletStates.hashCode ^
      notificationsGlobalEnabled.hashCode ^
      locale.hashCode ^
      appearances.hashCode ^
      providers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackgroundState &&
          runtimeType == other.runtimeType &&
          wallets == other.wallets &&
          notificationsWalletStates == other.notificationsWalletStates &&
          notificationsGlobalEnabled == other.notificationsGlobalEnabled &&
          locale == other.locale &&
          appearances == other.appearances &&
          providers == other.providers;
}
