// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class GasFeeHistoryInfo {
  final BigInt maxFee;
  final BigInt priorityFee;
  final BigInt baseFee;

  const GasFeeHistoryInfo({
    required this.maxFee,
    required this.priorityFee,
    required this.baseFee,
  });

  @override
  int get hashCode => maxFee.hashCode ^ priorityFee.hashCode ^ baseFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GasFeeHistoryInfo &&
          runtimeType == other.runtimeType &&
          maxFee == other.maxFee &&
          priorityFee == other.priorityFee &&
          baseFee == other.baseFee;
}

class GasInfo {
  final BigInt gasPrice;
  final BigInt maxPriorityFee;
  final GasFeeHistoryInfo feeHistory;
  final BigInt txEstimateGas;
  final BigInt blobBaseFee;

  const GasInfo({
    required this.gasPrice,
    required this.maxPriorityFee,
    required this.feeHistory,
    required this.txEstimateGas,
    required this.blobBaseFee,
  });

  @override
  int get hashCode =>
      gasPrice.hashCode ^
      maxPriorityFee.hashCode ^
      feeHistory.hashCode ^
      txEstimateGas.hashCode ^
      blobBaseFee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GasInfo &&
          runtimeType == other.runtimeType &&
          gasPrice == other.gasPrice &&
          maxPriorityFee == other.maxPriorityFee &&
          feeHistory == other.feeHistory &&
          txEstimateGas == other.txEstimateGas &&
          blobBaseFee == other.blobBaseFee;
}
