// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KeyPairInfo {
  final String sk;
  final String pk;

  const KeyPairInfo({
    required this.sk,
    required this.pk,
  });

  @override
  int get hashCode => sk.hashCode ^ pk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPairInfo &&
          runtimeType == other.runtimeType &&
          sk == other.sk &&
          pk == other.pk;
}
