// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BackgroundNotificationState {
  final bool transactions;
  final bool price;
  final bool security;
  final bool balance;

  const BackgroundNotificationState({
    required this.transactions,
    required this.price,
    required this.security,
    required this.balance,
  });

  @override
  int get hashCode =>
      transactions.hashCode ^
      price.hashCode ^
      security.hashCode ^
      balance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackgroundNotificationState &&
          runtimeType == other.runtimeType &&
          transactions == other.transactions &&
          price == other.price &&
          security == other.security &&
          balance == other.balance;
}
