// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ExplorerInfo {
  final String name;
  final String url;
  final String? icon;
  final int standard;

  const ExplorerInfo({
    required this.name,
    required this.url,
    this.icon,
    required this.standard,
  });

  @override
  int get hashCode =>
      name.hashCode ^ url.hashCode ^ icon.hashCode ^ standard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExplorerInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          icon == other.icon &&
          standard == other.standard;
}

class NetworkConfigInfo {
  final String name;
  final String logo;
  final String chain;
  final String shortName;
  final List<String> rpc;
  final Uint16List features;
  final BigInt chainId;
  final Uint64List chainIds;
  final int slip44;
  final BigInt diffBlockTime;
  final BigInt chainHash;
  final String? ens;
  final List<ExplorerInfo> explorers;
  final bool fallbackEnabled;
  final bool? testnet;

  const NetworkConfigInfo({
    required this.name,
    required this.logo,
    required this.chain,
    required this.shortName,
    required this.rpc,
    required this.features,
    required this.chainId,
    required this.chainIds,
    required this.slip44,
    required this.diffBlockTime,
    required this.chainHash,
    this.ens,
    required this.explorers,
    required this.fallbackEnabled,
    this.testnet,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      logo.hashCode ^
      chain.hashCode ^
      shortName.hashCode ^
      rpc.hashCode ^
      features.hashCode ^
      chainId.hashCode ^
      chainIds.hashCode ^
      slip44.hashCode ^
      diffBlockTime.hashCode ^
      chainHash.hashCode ^
      ens.hashCode ^
      explorers.hashCode ^
      fallbackEnabled.hashCode ^
      testnet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfigInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          logo == other.logo &&
          chain == other.chain &&
          shortName == other.shortName &&
          rpc == other.rpc &&
          features == other.features &&
          chainId == other.chainId &&
          chainIds == other.chainIds &&
          slip44 == other.slip44 &&
          diffBlockTime == other.diffBlockTime &&
          chainHash == other.chainHash &&
          ens == other.ens &&
          explorers == other.explorers &&
          fallbackEnabled == other.fallbackEnabled &&
          testnet == other.testnet;
}
