// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class NetworkConfigInfo {
  final String networkName;
  final BigInt chainId;
  final bool fallbackEnabled;
  final List<String> urls;
  final List<String> explorerUrls;
  final bool default_;

  const NetworkConfigInfo({
    required this.networkName,
    required this.chainId,
    required this.fallbackEnabled,
    required this.urls,
    required this.explorerUrls,
    required this.default_,
  });

  @override
  int get hashCode =>
      networkName.hashCode ^
      chainId.hashCode ^
      fallbackEnabled.hashCode ^
      urls.hashCode ^
      explorerUrls.hashCode ^
      default_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfigInfo &&
          runtimeType == other.runtimeType &&
          networkName == other.networkName &&
          chainId == other.chainId &&
          fallbackEnabled == other.fallbackEnabled &&
          urls == other.urls &&
          explorerUrls == other.explorerUrls &&
          default_ == other.default_;
}
