// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QrConfigInfo>>
abstract class QrConfigInfo implements RustOpaqueInterface {}

class QRcodeScanResultInfo {
  final String recipient;
  final String? provider;
  final String? tokenAddress;
  final String? amount;

  const QRcodeScanResultInfo({
    required this.recipient,
    this.provider,
    this.tokenAddress,
    this.amount,
  });

  @override
  int get hashCode =>
      recipient.hashCode ^
      provider.hashCode ^
      tokenAddress.hashCode ^
      amount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QRcodeScanResultInfo &&
          runtimeType == other.runtimeType &&
          recipient == other.recipient &&
          provider == other.provider &&
          tokenAddress == other.tokenAddress &&
          amount == other.amount;
}
