// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class WalletArgonParamsInfo {
  final int memory;
  final int iterations;
  final int threads;
  final String secret;

  const WalletArgonParamsInfo({
    required this.memory,
    required this.iterations,
    required this.threads,
    required this.secret,
  });

  @override
  int get hashCode =>
      memory.hashCode ^
      iterations.hashCode ^
      threads.hashCode ^
      secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletArgonParamsInfo &&
          runtimeType == other.runtimeType &&
          memory == other.memory &&
          iterations == other.iterations &&
          threads == other.threads &&
          secret == other.secret;
}

class WalletSettingsInfo {
  final Uint8List cipherOrders;
  final WalletArgonParamsInfo argonParams;
  final String? currencyConvert;
  final String? ipfsNode;
  final bool ensEnabled;
  final bool gasControlEnabled;
  final bool nodeRankingEnabled;
  final int maxConnections;
  final int requestTimeoutSecs;

  const WalletSettingsInfo({
    required this.cipherOrders,
    required this.argonParams,
    this.currencyConvert,
    this.ipfsNode,
    required this.ensEnabled,
    required this.gasControlEnabled,
    required this.nodeRankingEnabled,
    required this.maxConnections,
    required this.requestTimeoutSecs,
  });

  @override
  int get hashCode =>
      cipherOrders.hashCode ^
      argonParams.hashCode ^
      currencyConvert.hashCode ^
      ipfsNode.hashCode ^
      ensEnabled.hashCode ^
      gasControlEnabled.hashCode ^
      nodeRankingEnabled.hashCode ^
      maxConnections.hashCode ^
      requestTimeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSettingsInfo &&
          runtimeType == other.runtimeType &&
          cipherOrders == other.cipherOrders &&
          argonParams == other.argonParams &&
          currencyConvert == other.currencyConvert &&
          ipfsNode == other.ipfsNode &&
          ensEnabled == other.ensEnabled &&
          gasControlEnabled == other.gasControlEnabled &&
          nodeRankingEnabled == other.nodeRankingEnabled &&
          maxConnections == other.maxConnections &&
          requestTimeoutSecs == other.requestTimeoutSecs;
}
