// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class U64Array2 extends NonGrowableListView<BigInt> {
  static const arraySize = 2;

  @internal
  Uint64List get inner => _inner;
  final Uint64List _inner;

  U64Array2(this._inner)
      : assert(_inner.length == arraySize),
        super(_inner);

  U64Array2.init() : this(Uint64List(arraySize));
}
