// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'base_token.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transaction_metadata.dart';

class HistoricalTransactionInfo {
  final TransactionStatusInfo status;
  final TransactionMetadataInfo metadata;
  final String? evm;
  final String? scilla;
  final String? btc;
  final String? signedMessage;
  final BigInt timestamp;

  const HistoricalTransactionInfo({
    required this.status,
    required this.metadata,
    this.evm,
    this.scilla,
    this.btc,
    this.signedMessage,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      metadata.hashCode ^
      evm.hashCode ^
      scilla.hashCode ^
      btc.hashCode ^
      signedMessage.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoricalTransactionInfo &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          metadata == other.metadata &&
          evm == other.evm &&
          scilla == other.scilla &&
          btc == other.btc &&
          signedMessage == other.signedMessage &&
          timestamp == other.timestamp;
}

enum TransactionStatusInfo {
  pending,
  success,
  failed,
  ;
}
