[package]
name = "rust_lib_zilpay"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
once_cell = "1.19.0"
zilpay_core = { path = "/Users/rinat/projects/zilpay/zilpay-core" }
