// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../ledger_transport.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TRANSPORT_REGISTRY`, `TransportEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<String> nextConnectionId() =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplNextConnectionId();

Future<List<RustLedgerHidDevice>> ledgerHidList() =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplLedgerHidList();

Future<String> ledgerHidOpen({required String deviceId}) => RustLib.instance.api
    .crateApiLedgerTransportDesktopImplLedgerHidOpen(deviceId: deviceId);

Future<Uint8List> ledgerHidExchange(
        {required String connectionId, required List<int> apdu}) =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplLedgerHidExchange(
        connectionId: connectionId, apdu: apdu);

Future<void> ledgerHidClose({required String connectionId}) =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplLedgerHidClose(
        connectionId: connectionId);

Future<List<RustLedgerBleDevice>> ledgerBleScan() =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplLedgerBleScan();

Future<String> ledgerBleOpen({required String deviceId}) => RustLib.instance.api
    .crateApiLedgerTransportDesktopImplLedgerBleOpen(deviceId: deviceId);

Future<Uint8List> ledgerBleExchange(
        {required String connectionId, required List<int> apdu}) =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplLedgerBleExchange(
        connectionId: connectionId, apdu: apdu);

Future<void> ledgerBleClose({required String connectionId}) =>
    RustLib.instance.api.crateApiLedgerTransportDesktopImplLedgerBleClose(
        connectionId: connectionId);
