// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> tryUnlockWithSession({required BigInt walletIndex}) =>
    RustLib.instance.api
        .crateApiAuthTryUnlockWithSession(walletIndex: walletIndex);

Future<bool> tryUnlockWithPassword(
        {required String password,
        required BigInt walletIndex,
        List<String>? identifiers}) =>
    RustLib.instance.api.crateApiAuthTryUnlockWithPassword(
        password: password, walletIndex: walletIndex, identifiers: identifiers);

Future<List<String>> getBiometricType() =>
    RustLib.instance.api.crateApiAuthGetBiometricType();
