// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/account.dart';
import '../models/background.dart';
import '../models/ftoken.dart';
import '../models/notification.dart';
import '../models/provider.dart';
import '../models/settings.dart';
import '../models/wallet.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BackgroundState> loadService({required String path}) =>
    RustLib.instance.api.crateApiBackendLoadService(path: path);

Future<void> stopService() => RustLib.instance.api.crateApiBackendStopService();

Stream<int> tick() => RustLib.instance.api.crateApiBackendTick();

Future<bool> isServiceRunning() =>
    RustLib.instance.api.crateApiBackendIsServiceRunning();

Future<void> startWorker() => RustLib.instance.api.crateApiBackendStartWorker();

Future<BackgroundState> getData() =>
    RustLib.instance.api.crateApiBackendGetData();
