// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Stream<String> startBackgroundService() =>
//     RustLib.instance.api.crateApiBgStartBackgroundService();

// Future<void> stopBackgroundService() =>
//     RustLib.instance.api.crateApiBgStopBackgroundService();

// Future<void> sendMessageToService({required String message}) =>
//     RustLib.instance.api.crateApiBgSendMessageToService(message: message);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BackgroundService>>
// abstract class BackgroundService implements RustOpaqueInterface {
//   static Future<BackgroundService> default_() =>
//       RustLib.instance.api.crateApiBgBackgroundServiceDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  // static Future<BackgroundService> newInstance() =>
  //     RustLib.instance.api.crateApiBgBackgroundServiceNew();

//   Future<void> sendMessage({required String message});

//   Stream<String> start();

//   Future<void> stop();
// }
