// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/book.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> addNewBookAddress(
        {required String name,
        required String addr,
        required BigInt net,
        required int slip44}) =>
    RustLib.instance.api.crateApiBookAddNewBookAddress(
        name: name, addr: addr, net: net, slip44: slip44);

Future<void> removeFromAddressBook({required String addr}) =>
    RustLib.instance.api.crateApiBookRemoveFromAddressBook(addr: addr);

Future<List<AddressBookEntryInfo>> getAddressBookList() =>
    RustLib.instance.api.crateApiBookGetAddressBookList();
