// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/connection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> createNewConnection({required ConnectionInfo conn}) =>
    RustLib.instance.api.crateApiConnectionsCreateNewConnection(conn: conn);

Future<void> addWalletToConnection(
        {required String domain, required BigInt walletIndex}) =>
    RustLib.instance.api.crateApiConnectionsAddWalletToConnection(
        domain: domain, walletIndex: walletIndex);

Future<List<ConnectionInfo>> getConnectionsList() =>
    RustLib.instance.api.crateApiConnectionsGetConnectionsList();
