// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/keypair.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> genBip39Words({required int count}) =>
    RustLib.instance.api.crateApiMethodsGenBip39Words(count: count);

Future<Uint64List> checkNotExistsBip39Words(
        {required List<String> words, required String lang}) =>
    RustLib.instance.api
        .crateApiMethodsCheckNotExistsBip39Words(words: words, lang: lang);

Future<KeyPairInfo> genKeypair() =>
    RustLib.instance.api.crateApiMethodsGenKeypair();

Future<KeyPairInfo> keypairFromSk({required String sk}) =>
    RustLib.instance.api.crateApiMethodsKeypairFromSk(sk: sk);

Future<bool> isCryptoAddress({required String addr}) =>
    RustLib.instance.api.crateApiMethodsIsCryptoAddress(addr: addr);

Future<void> initApp() => RustLib.instance.api.crateApiMethodsInitApp();
