// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<NetworkConfigInfo>> getProviders() =>
    RustLib.instance.api.crateApiNetworkGetProviders();

Future<NetworkConfigInfo> getProvider({required BigInt providerIndex}) =>
    RustLib.instance.api
        .crateApiNetworkGetProvider(providerIndex: providerIndex);

Future<void> addProvider({required NetworkConfigInfo config}) =>
    RustLib.instance.api.crateApiNetworkAddProvider(config: config);

Future<void> removeProvider({required BigInt providerIndex}) =>
    RustLib.instance.api
        .crateApiNetworkRemoveProvider(providerIndex: providerIndex);

Future<void> selectProvider(
        {required BigInt providerIndex, required BigInt walletIndex}) =>
    RustLib.instance.api.crateApiNetworkSelectProvider(
        providerIndex: providerIndex, walletIndex: walletIndex);
