// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Stream<String> startBackgroundService() =>
    RustLib.instance.api.crateApiSimpleStartBackgroundService();

void stopBackgroundService() =>
    RustLib.instance.api.crateApiSimpleStopBackgroundService();

void sendMessageToService({required String message}) =>
    RustLib.instance.api.crateApiSimpleSendMessageToService(message: message);

Future<String> genBip39Words({required int count}) =>
    RustLib.instance.api.crateApiSimpleGenBip39Words(count: count);

Future<String> addBip39Wallet(
        {required String password,
        required String mnemonicStr,
        required Uint64List indexes,
        required Uint64List netCodes}) =>
    RustLib.instance.api.crateApiSimpleAddBip39Wallet(
        password: password,
        mnemonicStr: mnemonicStr,
        indexes: indexes,
        netCodes: netCodes);
